ReactiveCircus/android-emulator-runner

.github/workflows/workflow.yml
README.md
__tests__/input-validator.test.ts
action.yml
lib/emulator-manager.js
lib/input-validator.js
lib/main.js
src/emulator-manager.ts
src/input-validator.ts
src/main.ts

- Added `emulator-options` action input for providing command-line options when launching the emulator. Default is `-no-window -no-snapshot -noaudio -no-boot-anim`
- Removed `headless` action input
resolves #6

Add support for emulator options

---

.github/workflows/workflow.yml
README.md
__tests__/input-validator.test.ts
action.yml
lib/input-validator.js
lib/main.js
lib/sdk-installer.js
src/input-validator.ts
src/main.ts
src/sdk-installer.ts

Resolves #11 
Currently the `sdkmanager` installs the latest emulator binary from the stable channel, which means  when a new release of the emulator has issues, projects using this action will start breaking.
Pinning the emulator binary to a specific version requires a list of `[emulator binary version : download url mappings]` which isn't currently available ([feature request](https://issuetracker.google.com/issues/145943301)).
Therefore as a temporary solution we allow users to provide the emulator build number as an input and we'll use this to derive the download url - `emulator-darwin-<build-number>` and download the emulator binary directly instead of using the `sdkmanager`.
This is a temporary solution for users who need to pin the emulator build or when stable release breaks again …

Add support for pinning emulator build

---

.github/workflows/workflow.yml
README.md
action.yml
lib/emulator-manager.js
lib/main.js
src/emulator-manager.ts
src/main.ts

Resolves #59.
Added an action input `avd-name` for specifying a custom name used for creating the Android Virtual Device.

Add support for specifying a custom name used for creating AVD.

---

README.md

@ychescale9 solid work here 💪. Thank you!
- Mentioned [ci-matters](https://github.com/vgaidarji/ci-matters) repo in the list of adopters. Started using action in https://github.com/vgaidarji/ci-matters/pull/37.

Mention ci-matters repo in adopters list

---

.github/workflows/workflow.yml
lib/sdk-installer.js
src/sdk-installer.ts
test-fixture/app/build.gradle
test-fixture/gradle/wrapper/gradle-wrapper.properties

Resolves #70 
- Update build tools to `30.0.0`
- Add license required for API 30 system images
- Update test project's `targetSdk` and `compileSdk` to `30`
**Currently only `google_apis` system images are available for API 30**.

Support API 30

---

.github/workflows/workflow.yml
README.md
__tests__/input-validator.test.ts
action.yml
lib/input-validator.js
lib/main.js
src/input-validator.ts
src/main.ts
test-fixture/gradle.properties
test-fixture/gradle/wrapper/gradle-wrapper.properties

Resolves #98.
Added a new `playstore` option for `target` to support using system images with the `google_apis_playstore` target:
```
- name: run tests
uses: reactivecircus/android-emulator-runner@v2
with:
api-level: 30
target: playstore
arch: x86
script: ./gradlew connectedCheck
```

Add support for using google_apis_playstore system images.

---

README.md

Shopify/android-testify uses the Android Emulator Runner for GitHub Actions

Add Shopify/android-testify to list of projects

---

lib/emulator-manager.js
lib/sdk-installer.js
src/emulator-manager.ts
src/sdk-installer.ts
test-fixture/app/build.gradle
test-fixture/build.gradle
test-fixture/gradle.properties
test-fixture/gradle/wrapper/gradle-wrapper.properties

Replace usages of deprecated ANDROID_HOME with ANDROID_ROOT_SDK.
Bump build tools to 30.0.3.
Update test-fixture dependencies.

Update build tools

---

.github/workflows/workflow.yml
lib/sdk-installer.js
src/sdk-installer.ts

`google_apis` and `google_apis_playstore` API 28 system images require the `android-sdk-arm-dbt-license` license file, like API 30 system images. This patch updates the check for `android-sdk-arm-dbt-license` to include API 28 system images. The workflow configuration has also been updated to test API 28.

Support non-default API 28 images

---

.github/workflows/workflow.yml
lib/sdk-installer.js
src/sdk-installer.ts

Always add path for cmdline-tools to support macos-11.0.

---

.github/workflows/workflow.yml
README.md
action.yml
lib/emulator-manager.js
lib/main.js
src/emulator-manager.ts
src/main.ts

As discussed in https://github.com/ReactiveCircus/android-emulator-runner/issues/126, the emulator being set up by `avdmanager` in the new command-line tools only uses 1 core, which affects the stability of the emulator negatively sometimes.
In our experience, 2 cores seem to be pretty solid with no (or almost no) System UI ANR dialogs being shown on boot.
Appending a new line with a duplicate `hw.cpu.ncore` overrides other lines defining the same property before it.
Please let me know if you'd like me to add this option in `workflow.yml` file as well so that the tests include this option as well. Wasn't sure about updating that.

Add option to modify the number of cores

---

lib/main.js
src/main.ts

The exec() command only runs a program with literal argument strings.
It does not know how to do things like expanding environment variables,
or piping/redirection.  Hence the way to get "shell intelligence"
is to use exec() to run the `sh` process with the command line string
as a parameter.
But the method being used to do this was:
exec.exec(`sh -c \\"${script}"`)
This has problems, because wrapping the script in quotes creates
issues when the script itself contains quotes.  Escaping the string
correctly is a non-trivial problem, which also would create "noise"
in the debug output which would add confusion.
http://mywiki.wooledge.org/BashFAQ/050
The easiest way to work around this here is to use the array form of
exec() to pass exactly two parameters to `sh`.  No manipulation of the …

Avoid Wrapping Script Code In Quotes

---

README.md

Add kiwix-android to the list of projects that use ReactiveCircus/android-emulator-runner

Add kiwix-android to the list of projects that use android-emulator-runner

---

README.md
action.yml
lib/input-validator.js
src/input-validator.ts

Fixes https://github.com/ReactiveCircus/android-emulator-runner/issues/145

Add support for arm64-v8a for Apple Silicon Macs

---

README.md
__tests__/input-validator.test.ts
action.yml
lib/emulator-manager.js
lib/input-validator.js
lib/main.js
src/emulator-manager.ts
src/input-validator.ts
src/main.ts

Adds option to override Linux hardware acceleration (which works on AWS Bare Metal machines for example), referenced in #153 + updated docs.
Also relevant for #46.

Add option to toggle Linux hardware acceleration

---

.github/workflows/workflow.yml
README.md
__tests__/input-validator.test.ts
action.yml
lib/emulator-manager.js
lib/input-validator.js
lib/main.js
lib/sdk-installer.js
src/emulator-manager.ts
src/input-validator.ts
src/main.ts
src/sdk-installer.ts

Add `force-avd-creation` which when set to `false` will skip avd creation if avd with same name exists.
Setting `force-avd-creation` to `false` allows cached AVD to be used when starting emulator which significantly reduces emulator startup time from **1-3 minutes** down to **~15 seconds**.
Snapshot caching can be done by running the action with snapshot (no `-no-snapshot` in `emulator-options`) if no snapshot cache is found, before running the action again (with `-no-snapshot-save` to make sure the cache won't be updated after running tests) to run to actual tests:
```
- uses: actions/cache@v2
id: avd-cache
with:
path: |
~/.android/avd/*
~/.android/adb*
key: avd-${{ matrix.api-level }}
- name: generate snapshot for caching
if: steps.avd-cache.outputs.cache-hit != 'true'
uses: …
```

Support AVD snapshot caching

---

.github/workflows/workflow.yml
README.md
action.yml
lib/emulator-manager.js
lib/main.js
src/emulator-manager.ts
src/main.ts

Resolves #139.
Added `ram-size` option. This is taken from @AfzalivE 's  changes in the [Todoist fork](https://github.com/Doist/android-emulator-runner).

Add option to set AVD RAM size.

---

README.md
__tests__/input-validator.test.ts
action.yml
lib/input-validator.js
src/input-validator.ts

Expands the target allowlist to include `android-wear`, `android-wear-cn`, `android-tv` and `google-tv`, bringing the total number of allowed targets to 7.
This fixes #175

Support non-mobile targets (Wear OS, TV)

---

README.md

[Realm JavaScript](https://github.com/realm/realm-js) is using Android Emulator Runner to run our integration tests on Android.

Realm JavaScript is using Android Emulator Runner

---

README.md
__tests__/input-validator.test.ts
action.yml
lib/emulator-manager.js
lib/input-validator.js
lib/main.js
src/emulator-manager.ts
src/input-validator.ts
src/main.ts

Resolves #207.
This is basically taken from the Doist fork [here](https://github.com/Doist/android-emulator-runner/commit/4b6ca99f0d657662beca3eb0c22d8e254fbd5b31).

Add support for enabling hardware keyboard.

---

README.md
__tests__/input-validator.test.ts
action.yml
src/emulator-manager.ts
src/input-validator.ts
src/main.ts

Android has two drives - main storage for apps and external storage for downloads and user files.
`sdcard-path-or-size` controls the second - external storage.
Older devices default to 800M main storage. After the system apps, there is 309M left.
Most today's apps take more than that. Debug versions are not minimized, instrumented tests take extra space. Long story short - my app cannot fit. I get `INSTALL_FAILED_INSUFFICIENT_STORAGE` and related errors. Issue #184 is caused by this.
There is no option in `avdcreate`, but `/Users/runner/.android/avd/${avdName}.avd/config.ini` has the config option we want: `disk.dataPartition.size=800M`
This PR would allow appending a new `disk.dataPartition.size` size, when supplied as action argument named `disk-size`.
Until this or similar PR is …

Allow increasing main storage size (sdcard is separate storage)

---

README.md

https://github.com/wikimedia/apps-android-wikipedia/tree/master/.github/workflows 404's
https://github.com/wikimedia/apps-android-wikipedia/tree/master seems to be 9000 commits behind main
https://github.com/wikimedia/apps-android-wikipedia/blob/main/.github/workflows/android_smoke_test.yml (for example) references this action still
I think it wants to point to main instead?

README.md update: wikimedia have likely renamed master -> main

---

src/emulator-manager.ts
src/main.ts
src/sdk-installer.ts

Suggest reviewing with `diff -w` as the majority of the change is whitespace indentation.
https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#grouping-log-lines

Add GHA commands to group logs

---

README.md

Update README for using with gradle/gradle-build-action

---

README.md
action.yml
lib/emulator-manager.js
lib/main.js
src/emulator-manager.ts
src/main.ts

This change allows a user to specify the AVD heap size - all pretty much the same as setting RAM size.
Resolves #188

Add option to specify AVD heap size

---

__tests__/input-validator.test.ts
action.yml
lib/input-validator.js
lib/main.js
src/input-validator.ts
src/main.ts

Currently, this action disables hardware acceleration on Linux by default. This pull request adds an automatic detection of hardware acceleration on Linux. It does so by checking if /dev/kvm exists and accessible.
On GitHub hosted Linux runners, this introduces no behavior change as KVM is not supported there. However, we([BuildJet](https://buildjet.com/for-github-actions)) run a hosted GitHub Actions runner service which does support KVM on Linux. This change will help our customers to benefit from hardware acceleration on Linux.

Auto detect hardware acceleration on Linux

---

.github/workflows/action-types.yml
action-types.yml

Github Actions YAML usually isn't as useful as it could be.
https://github.com/krzema12/github-actions-typing
This project setup a way to define types for github actions inputs to build a type-safe DSL.
This commit implements both the typing for this action and the workflow to verify it.

Add action types

---

.github/workflows/main.yml
README.md
action-types.yml
action.yml
lib/main.js
src/main.ts

I added a new parameter `pre-emulator-launcher-script` (if you have better names, please let me know). With this parameter, you can pass a custom script which will be executed before launching the emulator (see #246 for more context).
I haven't written any unit tests, but added the `pre-emulator-launcher-script` to the CI of 1 job, so that we have 1 job with the parameter and 1 without the parameter. You can see here the ouput: https://github.com/nilsreichardt/android-emulator-runner/runs/6196378411?check_suite_focus=true#step:9:97
Closes #246

Pre Emulator Launch Script

---

README.md

Discussion: https://github.com/ReactiveCircus/android-emulator-runner/discussions/286
Also relevant: https://github.com/ReactiveCircus/android-emulator-runner/issues/46

Update README with latest info on default macOS Hypervisor and HAXM

---

__tests__/input-validator.test.ts
lib/input-validator.js
lib/main.js
lib/sdk-installer.js
src/emulator-manager.ts
src/input-validator.ts
src/main.ts
src/sdk-installer.ts

Support non-integer API level

---

action-types.yml
action.yml
lib/emulator-manager.js
lib/main.js
src/emulator-manager.ts
src/main.ts

Often, 10 minutes would not be enough for the emulator to boot on the machines I'm using
Add a new github action parameter so that the timeout is customisable

Add emulator-boot-timeout parameter

---

src/sdk-installer.ts

Previous code worked in a wrong way. 
1. Getting the first char of a build number is mistake because now numbers start with 1, but whole number higher than the number which starts from 7.
2. URL was incorrect for arm mac machines. It needed to add `aarch64` suffix

Fixed emulator download URL

---

.github/workflows/action-types.yml
.github/workflows/main.yml
.github/workflows/manually.yml
README.md

Reduce warnings:
> Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3, gradle/wrapper-validation-action@v1, actions/setup-java@v3, actions/cache@v3, gradle/gradle-build-action@v2. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
wrapper-validation doesn't have a version yet: https://github.com/gradle/wrapper-validation-action/issues/160 (it's quite possible it'll end up as `gradle/actions/wrapper-validation@v2` in a few weeks)
Note: most actions treat Node 20 as major bumps because self-hosted runners break down from automatic minor bumps via `@vX`, if there's no Node 20 installed on them.

Migrate to Node 20 on CI via GitHub Actions major upgrades

---

.github/workflows/main.yml
.github/workflows/manually.yml

* Follow-up on https://github.com/ReactiveCircus/android-emulator-runner/pull/372
* v2 points to https://github.com/gradle/wrapper-validation-action/releases/tag/v2.0.0-rc.1
Fixes warnings on https://github.com/ReactiveCircus/android-emulator-runner/actions/runs/7678503170
> Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: gradle/wrapper-validation-action@v1. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

Bump Gradle wrapper validation from v1 to v2 to use Node 20

---

README.md
__tests__/input-validator.test.ts
action-types.yml
action.yml
lib/emulator-manager.js
lib/input-validator.js
lib/main.js
src/emulator-manager.ts
src/input-validator.ts
src/main.ts

Currently, this action uses ADB commands without specifying device/emulator to use.
This is fine for GitHub-hosted machines, as they are isolated from each other, but becomes a problem when using this action on self-hosted machine, as ADB commands will fail if there are multiple devices present, and it wasn't specified which one to use.
Adding `emulator-port` input, that allows a job to specify port to start emulator on.
This way, one machine could have up to 16 emulators running at the same time (due to constraints in port range) without interfering with each other.

Add port parameter

---

lib/sdk-installer.js
src/sdk-installer.ts

There's probably even more precision to be had, but this seems like a good step forward. This is a different approach to the same problem as #344. I'd be happy to close this in favor of that one!
Source files shouldn't matter for the purposes of this tool. There are a number of files.
```
% ls -R $ANDROID_HOME/sources/android-34 | wc -l       
17750
```

Avoid changing the owner of unnecessary files

---

.github/workflows/main.yml
.github/workflows/manually.yml
README.md
lib/sdk-installer.js
src/sdk-installer.ts
test-fixture/app/build.gradle
test-fixture/build.gradle
test-fixture/gradle/wrapper/gradle-wrapper.properties

Also fixed test workflow - changed `macos-latest` to `macos-13` as running on M1 mac isn't supported.

SDK build tools 35.0.0, command-line tools 16.0.

---

.github/workflows/main.yml
lib/sdk-installer.js
src/sdk-installer.ts

Fix SDK path issues with ubuntu-24.04

---

lib/sdk-installer.js
src/sdk-installer.ts

Seems like the issue with `24.04` has been fixed from upstream so the changes in https://github.com/ReactiveCircus/android-emulator-runner/pull/409 are no longer required.
Changing the owner of the Android SDK path is no longer needed so we're keeping that change.

Revert creating avd directory.

---

.github/workflows/main.yml
lib/sdk-installer.js
src/sdk-installer.ts

Fixes https://github.com/ReactiveCircus/android-emulator-runner/issues/400
Re-land https://github.com/ReactiveCircus/android-emulator-runner/pull/409 which was reverted in https://github.com/ReactiveCircus/android-emulator-runner/pull/414, as the avd cache generated after the initial fix made me think the change wasn't needed anymore because it works without it. The fix is indeed required as the action currently still fails without restoring the any avd cache that restores the now missing `avd` dir in ubuntu-24.04.

Fix avd path on ubuntu-24.04 - attempt 2

---

README.md
__tests__/input-validator.test.ts
action.yml
lib/input-validator.js
lib/main.js
src/input-validator.ts
src/main.ts

Hi there, we'd like to test using the new 16kb page size to make sure things work, but isn't working with the action here currently
As pointed out in the linked issue, it's a fairly trivial input validator change, so I thought I'd just propose a PR
Thanks!
- Fixes #403

fix: allow google_apis_ps16k as a valid target
